# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "act_versions", :force => true do |t|
    t.column "actor_id",    :integer
    t.column "use_case_id", :integer
    t.column "original_id", :integer
    t.column "version",     :integer
    t.column "deleted",     :boolean, :default => false, :null => false
  end

  create_table "actor_versions", :force => true do |t|
    t.column "project_id",  :integer
    t.column "name",        :text
    t.column "original_id", :integer
    t.column "version",     :integer
    t.column "deleted",     :boolean, :default => false, :null => false
  end

  create_table "actors", :force => true do |t|
    t.column "project_id", :integer
    t.column "name",       :text
  end

  create_table "acts", :force => true do |t|
    t.column "actor_id",    :integer
    t.column "use_case_id", :integer
  end

  create_table "project_versions", :force => true do |t|
    t.column "name",             :text
    t.column "created_by_id",    :integer
    t.column "main_use_case_id", :integer
    t.column "original_id",      :integer
    t.column "version",          :integer
    t.column "deleted",          :boolean, :default => false, :null => false
  end

  create_table "projects", :force => true do |t|
    t.column "name",             :text
    t.column "created_by_id",    :integer
    t.column "main_use_case_id", :integer
  end

  create_table "use_case_versions", :force => true do |t|
    t.column "project_id",  :integer
    t.column "name",        :text
    t.column "original_id", :integer
    t.column "version",     :integer
    t.column "deleted",     :boolean, :default => false, :null => false
  end

  create_table "use_cases", :force => true do |t|
    t.column "project_id", :integer
    t.column "name",       :text
  end

  create_table "users", :force => true do |t|
    t.column "name",               :string
    t.column "current_project_id", :integer
  end

  create_table "version_numbers", :force => true do |t|
    t.column "created_at", :datetime, :null => false
    t.column "user",       :string
  end

end
